apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeme-banking-eta-deploy
  labels:
    app: financeme-banking-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financeme-banking-eta-app
  template:
    metadata:
      labels:
        app: financeme-banking-eta-app
    spec:
      containers:
      - name: ffinanceme-banking-eta-container
        image: astitva911/financeme_banking
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: financeme-banking-eta-np-service
  labels:
    app: financeme-banking-eta-app
spec:
  selector:
    app: financeme-banking-eta-app

  type: NodePort
  ports:
  - nodePort: 31029 
    port: 8082
    targetPort: 8082
